nodeLinker: pnp

packageExtensions:
  '@storybook/nextjs@*':
    dependencies:
      webpack: '*'
  '@storybook/core-common@*':
    dependencies:
      '@storybook/nextjs': '*'

yarnPath: .yarn/releases/yarn-4.1.1.cjs
